### ISSUE TITLE
AttributeError: 'fiction.pyfiction.cartesian_obstruction_layout' object has no attribute 'is_dead'

### ISSUE THREAD

**Issue by xiaohangguo** [cda-tum/mnt-nanoplacer#2]
Traceback (most recent call last):
  File "/home/lvshuhang/nano_placement/NanoPlaceR/main.py", line 157, in <module>
    model.learn(
  File "/home/lvshuhang/nano_placement/NanoPlaceR/ppo_masked/ppo_mask/ppo_mask.py", line 529, in learn
    continue_training = self.collect_rollouts(
  File "/home/lvshuhang/nano_placement/NanoPlaceR/ppo_masked/ppo_mask/ppo_mask.py", line 309, in collect_rollouts
    new_obs, rewards, dones, infos = env.step(actions)
  File "/home/lvshuhang/.local/lib/python3.9/site-packages/stable_baselines3/common/vec_env/base_vec_env.py", line 163, in step
    return self.step_wait()
  File "/home/lvshuhang/.local/lib/python3.9/site-packages/stable_baselines3/common/vec_env/dummy_vec_env.py", line 54, in step_wait
    obs, self.buf_rews[env_idx], self.buf_dones[env_idx], self.buf_infos[env_idx] = self.envs[env_idx].step(
  File "/home/lvshuhang/.local/lib/python3.9/site-packages/stable_baselines3/common/monitor.py", line 95, in step
    observation, reward, done, info = self.env.step(action)
  File "/home/lvshuhang/.local/lib/python3.9/site-packages/gym/wrappers/order_enforcing.py", line 11, in step
    observation, reward, done, info = self.env.step(action)
  File "/home/lvshuhang/nano_placement/NanoPlaceR/placement_envs/envs/nano_placement_env.py", line 240, in step
    reward, done = self.calculate_reward(
  File "/home/lvshuhang/nano_placement/NanoPlaceR/placement_envs/envs/nano_placement_env.py", line 510, in calculate_reward
    optimize_post_placement(self.layout)
  File "/home/lvshuhang/nano_placement/NanoPlaceR/placement_envs/utils/post_placement_optimization.py", line 49, in optimize_post_placement
    fix_dead_nodes(layout, gates)
  File "/home/lvshuhang/nano_placement/NanoPlaceR/placement_envs/utils/post_placement_optimization.py", line 151, in fix_dead_nodes
    if lyt.is_dead(lyt.get_node(gate)):
AttributeError: 'fiction.pyfiction.cartesian_obstruction_layout' object has no attribute 'is_dead'

**Comment by xiaohangguo** [comment]
lvshuhang@s04:~/nano_placement/NanoPlaceR
$ python main.py 
New best placement: 1/150 (1.90s)
New best placement: 2/150 (1.91s)
New best placement: 3/150 (1.91s)
New best placement: 4/150 (1.91s)
New best placement: 5/150 (1.92s)
New best placement: 6/150 (1.92s)
New best placement: 7/150 (1.92s)
New best placement: 8/150 (1.93s)
New best placement: 9/150 (1.93s)
New best placement: 10/150 (1.93s)
New best placement: 11/150 (1.94s)
New best placement: 12/150 (1.94s)
New best placement: 13/150 (1.95s)
New best placement: 14/150 (1.95s)
New best placement: 15/150 (1.95s)
New best placement: 16/150 (1.96s)
New best placement: 17/150 (1.96s)
New best placement: 18/150 (1.96s)
New best placement: 19/150 (1.97s)
New best placement: 20/150 (1.97s)
New best placement: 21/150 (1.98s)
New best placement: 22/150 (1.98s)
New best placement: 23/150 (6.34s)
New best placement: 24/150 (6.34s)
New best placement: 25/150 (6.35s)
New best placement: 26/150 (15.13s)
New best placement: 27/150 (15.13s)
New best placement: 28/150 (15.14s)
New best placement: 29/150 (21.39s)
New best placement: 30/150 (21.40s)
New best placement: 31/150 (25.11s)
New best placement: 32/150 (33.27s)
New best placement: 33/150 (45.46s)
New best placement: 34/150 (45.47s)
New best placement: 35/150 (52.14s)
New best placement: 36/150 (52.14s)
New best placement: 37/150 (52.15s)
New best placement: 38/150 (52.15s)
New best placement: 39/150 (75.91s)
New best placement: 40/150 (75.92s)
New best placement: 41/150 (75.92s)
New best placement: 42/150 (80.72s)
New best placement: 43/150 (96.07s)
New best placement: 44/150 (96.08s)
New best placement: 45/150 (96.08s)
New best placement: 46/150 (96.09s)
New best placement: 47/150 (96.09s)
New best placement: 48/150 (96.09s)
New best placement: 49/150 (96.10s)
New best placement: 50/150 (96.10s)
New best placement: 51/150 (96.11s)
New best placement: 52/150 (96.12s)
New best placement: 53/150 (96.12s)
New best placement: 54/150 (99.01s)
New best placement: 55/150 (99.02s)
New best placement: 56/150 (99.02s)
New best placement: 57/150 (99.03s)
New best placement: 58/150 (99.03s)
New best placement: 59/150 (111.34s)
New best placement: 60/150 (111.35s)
New best placement: 61/150 (111.35s)
New best placement: 62/150 (111.36s)
New best placement: 63/150 (111.37s)
New best placement: 64/150 (111.38s)
New best placement: 65/150 (111.38s)
New best placement: 66/150 (198.01s)
New best placement: 67/150 (198.02s)
New best placement: 68/150 (198.02s)
New best placement: 69/150 (263.52s)
New best placement: 70/150 (263.52s)
New best placement: 71/150 (263.53s)
New best placement: 72/150 (419.67s)
New best placement: 73/150 (419.68s)
New best placement: 74/150 (419.68s)
New best placement: 75/150 (419.68s)
New best placement: 76/150 (419.69s)
New best placement: 77/150 (419.69s)
New best placement: 78/150 (419.69s)
New best placement: 79/150 (419.89s)
New best placement: 80/150 (419.89s)
New best placement: 81/150 (419.90s)
New best placement: 82/150 (744.21s)
New best placement: 83/150 (744.22s)
New best placement: 84/150 (744.22s)
New best placement: 85/150 (748.54s)
New best placement: 86/150 (748.54s)
New best placement: 87/150 (748.55s)
New best placement: 88/150 (748.55s)
New best placement: 89/150 (748.56s)
New best placement: 90/150 (778.96s)
New best placement: 91/150 (778.97s)
New best placement: 92/150 (781.61s)
New best placement: 93/150 (783.02s)
New best placement: 94/150 (784.60s)
New best placement: 95/150 (793.67s)
New best placement: 96/150 (793.67s)
New best placement: 97/150 (793.67s)
New best placement: 98/150 (798.83s)
New best placement: 99/150 (798.83s)
New best placement: 100/150 (798.84s)
New best placement: 101/150 (798.84s)
New best placement: 102/150 (804.97s)
New best placement: 103/150 (804.97s)
New best placement: 104/150 (804.98s)
New best placement: 105/150 (804.98s)
New best placement: 106/150 (804.99s)
New best placement: 107/150 (804.99s)
New best placement: 108/150 (805.00s)
New best placement: 109/150 (805.00s)
New best placement: 110/150 (805.01s)
New best placement: 111/150 (805.01s)
New best placement: 112/150 (805.03s)
New best placement: 113/150 (805.03s)
New best placement: 114/150 (805.04s)
New best placement: 115/150 (805.05s)
New best placement: 116/150 (805.05s)
New best placement: 117/150 (805.07s)
New best placement: 118/150 (805.08s)
New best placement: 119/150 (805.08s)
New best placement: 120/150 (805.08s)
New best placement: 121/150 (805.09s)
New best placement: 122/150 (805.10s)
New best placement: 123/150 (821.92s)
New best placement: 124/150 (821.93s)
New best placement: 125/150 (822.19s)
New best placement: 126/150 (891.73s)
New best placement: 127/150 (891.74s)
New best placement: 128/150 (891.75s)
New best placement: 129/150 (891.76s)
New best placement: 130/150 (891.77s)
New best placement: 131/150 (891.77s)
New best placement: 132/150 (891.78s)
New best placement: 133/150 (891.79s)
New best placement: 134/150 (891.80s)
New best placement: 135/150 (891.82s)
New best placement: 136/150 (891.83s)
New best placement: 137/150 (891.83s)
New best placement: 138/150 (891.84s)
New best placement: 139/150 (891.85s)
New best placement: 140/150 (951.61s)



New best placement: 141/150 (1537.50s)
New best placement: 142/150 (1537.51s)
New best placement: 143/150 (1537.52s)
New best placement: 144/150 (1537.52s)
New best placement: 145/150 (1537.53s)
New best placement: 146/150 (1537.54s)
New best placement: 147/150 (1537.55s)
New best placement: 148/150 (1559.97s)
New best placement: 149/150 (1559.98s)
New best placement: 150/150 (1920.84s)
Found solution after 1920.84s
Step: 1, Moved Gates: 110
Step: 2, Moved Gates: 49
Step: 3, Moved Gates: 3
Step: 4, Moved Gates: 5
Step: 5, Moved Gates: 3
Step: 6, Moved Gates: 0
Column 37 can be deleted
Traceback (most recent call last):
  File "/home/lvshuhang/nano_placement/NanoPlaceR/main.py", line 157, in <module>
    model.learn(
  File "/home/lvshuhang/nano_placement/NanoPlaceR/ppo_masked/ppo_mask/ppo_mask.py", line 529, in learn
    continue_training = self.collect_rollouts(
  File "/home/lvshuhang/nano_placement/NanoPlaceR/ppo_masked/ppo_mask/ppo_mask.py", line 309, in collect_rollouts
    new_obs, rewards, dones, infos = env.step(actions)
  File "/home/lvshuhang/.local/lib/python3.9/site-packages/stable_baselines3/common/vec_env/base_vec_env.py", line 163, in step
    return self.step_wait()
  File "/home/lvshuhang/.local/lib/python3.9/site-packages/stable_baselines3/common/vec_env/dummy_vec_env.py", line 54, in step_wait
    obs, self.buf_rews[env_idx], self.buf_dones[env_idx], self.buf_infos[env_idx] = self.envs[env_idx].step(
  File "/home/lvshuhang/.local/lib/python3.9/site-packages/stable_baselines3/common/monitor.py", line 95, in step
    observation, reward, done, info = self.env.step(action)
  File "/home/lvshuhang/.local/lib/python3.9/site-packages/gym/wrappers/order_enforcing.py", line 11, in step
    observation, reward, done, info = self.env.step(action)
  File "/home/lvshuhang/nano_placement/NanoPlaceR/placement_envs/envs/nano_placement_env.py", line 240, in step
    reward, done = self.calculate_reward(
  File "/home/lvshuhang/nano_placement/NanoPlaceR/placement_envs/envs/nano_placement_env.py", line 510, in calculate_reward
    optimize_post_placement(self.layout)
  File "/home/lvshuhang/nano_placement/NanoPlaceR/placement_envs/utils/post_placement_optimization.py", line 49, in optimize_post_placement
    fix_dead_nodes(layout, gates)
  File "/home/lvshuhang/nano_placement/NanoPlaceR/placement_envs/utils/post_placement_optimization.py", line 151, in fix_dead_nodes
    if lyt.is_dead(lyt.get_node(gate)):
AttributeError: 'fiction.pyfiction.cartesian_obstruction_layout' object has no attribute 'is_dead'

**Comment by simon1hofmann** [comment]
Thanks for raising this issue @xiaohangguo 

The error is due to a new post-layout optimization algorithm that depends on new functionality in pyfiction. 
Updating and reinstalling fiction should resolve the AttributeError.

`(venv) $ cd fiction`
`(venv) $ git pull`
`(venv) $ pip install .`

**Comment by xiaohangguo** [comment]
> Thanks for raising this issue @xiaohangguo
> 
> The error is due to a new post-layout optimization algorithm that depends on new functionality in pyfiction. Updating and reinstalling fiction should resolve the AttributeError.
> 
> `(venv) $ cd fiction` `(venv) $ git pull` `(venv) $ pip install .`

ok,solved it
